version: "3"

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: yarn watch
    volumes:
      - ./:/app:${CONSISTENCY:-cached}
    ports:
      - 3000:3000
