version: "3"

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: yarn start
    environment:
      LOCAL_IP: ${LOCAL_IP:-0.0.0.0}
    volumes:
      - ./:/app:${CONSISTENCY:-cached}
    ports:
      - 8080:8080
      - 8081:8081
